"""Survey the Mission Sunlight corpus (engine `peintre`).

Read-only over games/mission-sunlight/discs/cd. Writes into engines/peintre/notes/:

  binaries.md         every PE file: MD5, size, PE timestamp, linker, Rich header,
                      sections, imports, compiler guess. dx/ redistributables only counted.
  corpus-inventory.md layout, then extension x magic counts.
  corpus-md5.tsv      path, size, MD5 of every file.
  exe-strings.md      what names the program's origin: library banners, the PDB path,
                      registry key, data paths, and which DirectX interfaces it references.

    python engines/peintre/tools/survey.py
    python engines/peintre/tools/survey.py --selftest
"""

from __future__ import annotations

import argparse
import datetime
import hashlib
import re
import uuid
from collections import Counter, defaultdict
from pathlib import Path

import pefile

REPO = Path(__file__).resolve().parents[3]
NOTES = REPO / "engines/peintre/notes"
ROOT = REPO / "games/mission-sunlight/discs/cd"
EXE = ROOT / "Data/mission.___"
PE_EXTS = {".exe", ".dll", ".___"}
REDIST_DIRS = {"dx"}
# DirectX interface IDs the EXE could QueryInterface for (DirectX 5 SDK headers).
IIDS = {
    "IID_IDirectDraw2": "B3A6F3E0-2B43-11CF-A2DE-00AA00B93356",
    "IID_IDirectDrawSurface2": "57805885-6EEC-11CF-9441-A82303C10E27",
    "IID_IDirect3D": "3BBA0080-2421-11CF-A31A-00AA00B93356",
    "IID_IDirect3D2": "6AAE1EC1-662A-11D0-889D-00AA00BBB76A",
    "IID_IDirect3DHALDevice": "84E63DE0-46AA-11CF-816F-0000C020156E",
    "IID_IDirect3DRGBDevice": "A4665C60-2673-11CF-A31A-00AA00B93356",
    "IID_IDirect3DMMXDevice": "881949A1-D6F3-11D0-89AB-00A0C9054129",
    "IID_IDirect3DRampDevice": "F2086B20-259F-11CF-A31A-00AA00B93356",
    "IID_IDirect3DTexture": "2CDCD9E0-25A0-11CF-A31A-00AA00B93356",
    "IID_IDirect3DTexture2": "93281502-8CF8-11D0-89AB-00A0C9054129",
    "IID_IDirectSound3DBuffer": "279AFA86-4981-11CE-A521-0020AF0BE560",
}
BANNER_RE = re.compile(rb"[\x20-\x7e]*(?:CRYO|Cryo|GUILLANG|\.pdb|Copyright|\(C\))[\x20-\x7e]*")


def md5(path: Path) -> str:
    return hashlib.md5(path.read_bytes()).hexdigest()


def magic(head: bytes) -> str:
    """First four bytes as text when printable, else hex."""
    m = head[:4]
    if len(m) == 4 and all(32 <= b < 127 for b in m):
        return "'" + m.decode() + "'"
    return m.hex()


def rich(pe) -> str:
    rh = pe.parse_rich_header()
    if not rh:
        return "none"
    v = rh["values"]
    return ", ".join(f"id {v[i] >> 16} build {v[i] & 0xFFFF} x{v[i + 1]}" for i in range(0, len(v), 2))


def pe_info(path: Path) -> dict | None:
    blob = path.read_bytes()
    if blob[:2] != b"MZ":
        return None
    pe = pefile.PE(data=blob)
    fh, oh = pe.FILE_HEADER, pe.OPTIONAL_HEADER
    secs = [s.Name.rstrip(b"\0").decode("latin1") for s in pe.sections]
    ts = fh.TimeDateStamp
    imports = []
    for d in getattr(pe, "DIRECTORY_ENTRY_IMPORT", []):
        names = [(i.name or f"#{i.ordinal}".encode()).decode() for i in d.imports]
        imports.append((d.dll.decode(), names))
    linker = f"{oh.MajorLinkerVersion}.{oh.MinorLinkerVersion}"
    if b"WATCOM C/C++32" in blob:
        compiler = "Watcom C/C++32"
    elif b"Borland" in blob or "CODE" in secs:
        compiler = "Borland"
    else:
        compiler = "Microsoft"
    return {
        "kind": "DLL" if fh.Characteristics & 0x2000 else "EXE",
        "timestamp": f"0x{ts:08x} "
        + datetime.datetime.fromtimestamp(ts, datetime.UTC).strftime("%Y-%m-%d %H:%M:%S"),
        "linker": linker,
        "compiler": f"{compiler}, linker {linker}",
        "rich": rich(pe),
        "sections": secs,
        "imports": imports,
        "base": f"0x{oh.ImageBase:08x}",
        "entry": f"0x{oh.ImageBase + oh.AddressOfEntryPoint:08x}",
    }


def is_redist(rel: Path) -> bool:
    return any(p.lower() in REDIST_DIRS for p in rel.parts[:-1])


def survey() -> None:
    rows = []  # (rel, size, md5, magic, path)
    for path in sorted(p for p in ROOT.rglob("*") if p.is_file()):
        rel = path.relative_to(ROOT)
        with path.open("rb") as fh:
            head = fh.read(16)
        rows.append((rel, path.stat().st_size, md5(path), magic(head), path))
    NOTES.mkdir(parents=True, exist_ok=True)
    with (NOTES / "corpus-md5.tsv").open("w", encoding="utf-8", newline="\n") as out:
        out.write("path\tsize\tmd5\n")
        for rel, size, h, _, _ in rows:
            out.write(f"{rel.as_posix()}\t{size}\t{h}\n")
    write_binaries(rows)
    write_inventory(rows)
    write_exe_strings()


def write_binaries(rows) -> None:
    lines = ["# Binaries (Mission Sunlight CD)", "",
             "Generated by `engines/peintre/tools/survey.py`. Every PE file outside `dx/` (the",
             "DirectX 5 redistributables, only counted).", ""]
    redist = 0
    for rel, size, h, _, path in rows:
        if path.suffix.lower() not in PE_EXTS:
            continue
        if is_redist(rel):
            redist += 1
            continue
        info = pe_info(path)
        if info is None:
            continue
        lines += [f"## `{rel.as_posix()}`", "",
                  f"- {size:,} B, MD5 `{h}`, {info['kind']}, PE timestamp {info['timestamp']} UTC",
                  f"- {info['compiler']}; Rich header: {info['rich']}",
                  f"- image base {info['base']}, entry {info['entry']}; sections {' '.join(info['sections'])}",
                  "- imports:"]
        for dll, names in info["imports"]:
            lines.append(f"  - {dll} ({len(names)}): {' '.join(names)}")
        lines.append("")
    lines += [f"DirectX redistributable PE files skipped: {redist}", ""]
    (NOTES / "binaries.md").write_text("\n".join(lines), encoding="utf-8")


def write_inventory(rows) -> None:
    sel = [r for r in rows if not is_redist(r[0])]
    lines = ["# Corpus inventory (Mission Sunlight CD)", "",
             "Generated by `engines/peintre/tools/survey.py`. Regenerate rather than hand-edit.",
             "Magic = first four bytes, quoted when printable, else hex. `dx/` excluded from the",
             "extension table.", "",
             f"Root `games/mission-sunlight/discs/cd`: {len(rows):,} files, "
             f"{sum(r[1] for r in rows):,} bytes ({len(rows) - len(sel)} in `dx/`).", "",
             "Layout (files per directory):", ""]
    for d, n in sorted(Counter("/".join(r[0].parts[:-1]) or "." for r in rows).items()):
        lines.append(f"- `{d}/` {n}")
    lines += ["", "| Ext | Files | Bytes | Magics (count) | Directories |", "|---|---:|---:|---|---|"]
    by_ext = defaultdict(list)
    for r in sel:
        by_ext[r[0].suffix.lower() or "(none)"].append(r)
    for ext, rs in sorted(by_ext.items(), key=lambda kv: -len(kv[1])):
        mags = Counter(r[3] for r in rs)
        top = ", ".join(f"`{m}` {n}" for m, n in mags.most_common(6))
        if len(mags) > 6:
            top += f", … {len(mags)} distinct"
        dirs = ", ".join(sorted({"/".join(r[0].parts[:-1]) or "." for r in rs}))
        lines.append(f"| `{ext}` | {len(rs):,} | {sum(r[1] for r in rs):,} | {top} | {dirs} |")
    (NOTES / "corpus-inventory.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_exe_strings() -> None:
    blob = EXE.read_bytes()
    lines = ["# Origin strings of `Data/mission.___`", "",
             "Generated by `engines/peintre/tools/survey.py`: library banners, build path,",
             "registry key, and a search for DirectX interface IDs (little-endian GUIDs).", "",
             "## Banners and paths", ""]
    for m in BANNER_RE.finditer(blob):
        if len(m.group()) >= 8:
            lines.append(f"- file offset 0x{m.start():06x}: `{m.group().decode('latin1')}`")
    lines += ["", "## DirectX interface IDs", "", "| IID | File offset |", "|---|---|"]
    for name, g in IIDS.items():
        i = blob.find(uuid.UUID(g).bytes_le)
        lines.append(f"| {name} | {'absent' if i < 0 else f'0x{i:06x}'} |")
    lines += ["", "## Data paths (format strings)", ""]
    for m in re.finditer(rb"[\x20-\x7e]*(?:DATA|SAVE)\\[\x20-\x7e]*", blob):
        lines.append(f"- 0x{m.start():06x}: `{m.group().decode('latin1')}`")
    (NOTES / "exe-strings.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


def selftest() -> None:
    assert magic(b"HNM6....") == "'HNM6'"
    assert magic(b"\x34\x00\x00\x00") == "34000000"
    assert is_redist(Path("dx/dx5eng.exe")) and not is_redist(Path("Data/mission.___"))
    assert uuid.UUID(IIDS["IID_IDirectDraw2"]).bytes_le[:4] == bytes.fromhex("e0f3a6b3")
    print("selftest ok")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--selftest", action="store_true")
    if ap.parse_args().selftest:
        selftest()
    else:
        survey()
