"""Gilbert.exe's Delphi resources: the form streams (RCDATA TPF0) and PACKAGEINFO's unit list.

Writes engines/gilbert/notes/exe-forms.md (read-only over the disc).

    python engines/gilbert/tools/exeres.py
    python engines/gilbert/tools/exeres.py --selftest
"""

from __future__ import annotations

import struct
import sys
from pathlib import Path

import pefile

sys.path.insert(0, str(Path(__file__).parent / "parsers"))
from wxi import Reader, read_value  # noqa: E402

REPO = Path(__file__).resolve().parents[3]
EXE = REPO / "games/gilbert/discs/cd/Program/Gilbert.exe"
OUT = REPO / "engines/gilbert/notes/exe-forms.md"


def read_object(r: Reader, depth: int, out: list[str]) -> None:
    flags = r.d[r.p]
    if flags & 0xF0 == 0xF0:  # ffInherited/ffChildPos/ffInline prefix
        r.u8()
        if flags & 2:
            read_value(r)
    cls, name = r.sstr(), r.sstr()
    out.append(f"{'  ' * depth}- **{name}**: {cls}")
    while (prop := r.sstr()) != "":
        v = read_value(r)
        if isinstance(v, bytes):
            v = f"<{len(v)} bytes>"
        elif isinstance(v, list):
            v = f"<collection of {len(v)}>"
        out.append(f"{'  ' * depth}  - {prop} = {v!r}")
    while r.d[r.p] != 0:
        read_object(r, depth + 1, out)
    r.u8()


def package_units(blob: bytes) -> list[tuple[int, str]]:
    """PACKAGEINFO: flags u32, requires count u32 + (hash u8, name\0),
    contains count u32 + (flags u8, hash u8, name\0)."""
    r = Reader(blob)
    r.unpack("I")
    units = []
    for _ in range(r.unpack("I")):  # required packages
        r.u8()
        units.append((-1, r.take(blob.index(b"\0", r.p) - r.p + 1)[:-1].decode("latin1")))
    for _ in range(r.unpack("I")):
        fl = r.u8()
        r.u8()
        units.append((fl, r.take(blob.index(b"\0", r.p) - r.p + 1)[:-1].decode("latin1")))
    return units


def main() -> None:
    pe = pefile.PE(str(EXE))
    rc = next(t for t in pe.DIRECTORY_ENTRY_RESOURCE.entries if t.struct.Id == 10)
    lines = ["# Gilbert.exe: Delphi forms and units", "",
             "Generated by `engines/gilbert/tools/exeres.py` from the RCDATA resources.", ""]
    for e in rc.directory.entries:
        data_entry = e.directory.entries[0].data.struct
        blob = pe.get_data(data_entry.OffsetToData, data_entry.Size)
        name = str(e.name)
        if blob[:4] == b"TPF0":
            lines += [f"## Form `{name}`", ""]
            r = Reader(blob, 4)
            read_object(r, 0, lines)
            assert r.p == len(blob), f"{name}: {len(blob) - r.p} bytes left"
            lines.append("")
        elif name == "PACKAGEINFO":
            units = package_units(blob)
            lines += ["## PACKAGEINFO: units linked into the program", "",
                      "Flags byte per unit as Delphi writes it; the order is the link order.", ""]
            lines += [f"- `{u}`" + ("" if fl < 0 else f" (0x{fl:02x})") for fl, u in units]
            lines.append("")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(REPO)}")


def selftest() -> None:
    blob = b"\x06TgMain\x05gMain\x04Left\x02\x05\x00\x06TImage\x02im\x00\x00\x00"
    out: list[str] = []
    r = Reader(blob)
    read_object(r, 0, out)
    assert r.p == len(blob) and out[0] == "- **gMain**: TgMain" and out[2] == "  - **im**: TImage"
    info = struct.pack("<II", 0, 0) + struct.pack("<I", 1) + b"\x10\x55gilbert\0"
    assert package_units(info) == [(0x10, "gilbert")]
    print("selftest ok")


if __name__ == "__main__":
    selftest() if sys.argv[1:] == ["--selftest"] else main()
