"""Generate the engine's media name table (../scummvm/engines/ring/medianames.h) from
engines/ring/notes/media-names.tsv (namemap.py, spec/editions.md "Names"): one row per DVD
file name whose CD/ISO name differs, looked up by name alone (DVD numbers are unique across
zones; a file's rows in several language folders all give the same name).

    python engines/ring/tools/medianames.py             # writes the header
    python engines/ring/tools/medianames.py --selftest  # checks the table is a function
"""

from __future__ import annotations

import csv
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
TSV = REPO / "engines/ring/notes/media-names.tsv"
OUT = Path("C:/scummvm/engines/ring/medianames.h")

HEADER = """/* ScummVM - Graphic Adventure Engine
 *
 * ScummVM is the legal property of its developers, whose names
 * are too numerous to list here. Please refer to the COPYRIGHT
 * file distributed with this source distribution.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

// Generated by the research repository's engines/ring/tools/medianames.py from
// notes/media-names.tsv (spec/editions.md, "Names"): the DVD's file names and the CD and
// ISO versions' names for the same files. Do not edit.

#ifndef RING_MEDIANAMES_H
#define RING_MEDIANAMES_H

namespace Ring {

static const struct {
	const char *dvd, *name;
} kMediaNames[] = {
"""


def table() -> dict[str, str]:
    names: dict[str, str] = {}
    with TSV.open(encoding="utf-8") as f:
        for row in csv.DictReader(f, delimiter="\t"):
            dvd, name = row["dvd"].lower(), row["name"].lower()
            if names.get(dvd, name) != name:
                raise SystemExit(f"{dvd}: {names[dvd]} and {name}")
            names[dvd] = name
    return names


def main() -> None:
    names = table()
    if "--selftest" in sys.argv:
        assert names["1626.wac"] == "cin_rh1_01.wac", names["1626.wac"]
        assert names["up_gun.tga"] == "larup_gun.tga"
        assert len(names) > 900
        print(f"selftest ok: {len(names)} names")
        return
    lines = [HEADER]
    for dvd in sorted(names):
        lines.append(f'\t{{ "{dvd}", "{names[dvd]}" }},\n')
    lines.append("};\n\n} // End of namespace Ring\n\n#endif // RING_MEDIANAMES_H\n")
    OUT.write_text("".join(lines), encoding="utf-8", newline="\n")
    print(f"{OUT}: {len(names)} names")


if __name__ == "__main__":
    main()
