"""Survey the Ring-engine corpus: every edition of Ring and Prophet and the Assassin.

Read-only over games/*/discs. Writes into engines/ring/notes/:

  binaries.md         every PE file (EXE/DLL/BPL/renamed .ex_): MD5, size, PE timestamp,
                      linker version, sections, compiler guess. DirectX redistributables
                      are only counted.
  corpus-inventory.md per edition: top-level layout, then extension x magic counts.
  corpus-md5.tsv      edition, path, size, MD5 of every file (the basis of the next file).
  identical-files.md  which files are byte-identical across editions.

    python engines/ring/tools/survey.py            # hashes ~10 GB, a few minutes
    python engines/ring/tools/survey.py --selftest
"""

from __future__ import annotations

import argparse
import datetime
import hashlib
import sys
from collections import Counter, defaultdict
from pathlib import Path

import pefile

REPO = Path(__file__).resolve().parents[3]
NOTES = REPO / "engines/ring/notes"
EDITIONS = {
    "ring/dvd": "games/ring/discs/dvd-edition",
    **{f"ring/cd{i}": f"games/ring/discs/cd-version/disc{i}" for i in range(1, 7)},
    **{f"ring/iso{i}": f"games/ring/discs/iso-version/disc{i}" for i in range(1, 5)},
    "prophet/cd1": "games/prophet-and-assassin/discs/cd1",
    "prophet/cd2": "games/prophet-and-assassin/discs/cd2",
}
PE_EXTS = {".exe", ".dll", ".bpl", ".ex_", ".cpl", ".drv", ".sys", ".x86"}
REDIST_DIRS = {"directx", "drivers"}


def md5(path: Path) -> str:
    h = hashlib.md5()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def magic(head: bytes) -> str:
    """First four bytes as text when printable, else hex."""
    m = head[:4]
    if len(m) == 4 and all(32 <= b < 127 for b in m):
        return "'" + m.decode() + "'"
    return m.hex()


def compiler_guess(sections: list[str], linker: str, blob: bytes) -> str:
    if "CODE" in sections or b"Borland" in blob[:0x200000]:
        tag = "Borland"
        if b"Borland C++" in blob or b"bcbsmp" in blob.lower() or b"@@" in blob:
            tag = "Borland C++ (Builder)" if b"vcl" in blob.lower() else "Borland C++"
        return f"{tag}, linker {linker}"
    if ".text" in sections:
        return f"Microsoft, linker {linker}"
    return f"unknown, linker {linker}"


def pe_info(path: Path) -> dict | None:
    blob = path.read_bytes()
    if blob[:2] != b"MZ":
        return None
    try:
        pe = pefile.PE(data=blob, fast_load=True)
    except pefile.PEFormatError:
        return {"kind": "MZ (not PE)"}
    fh, oh = pe.FILE_HEADER, pe.OPTIONAL_HEADER
    secs = [s.Name.rstrip(b"\0").decode("latin1") for s in pe.sections]
    linker = f"{oh.MajorLinkerVersion}.{oh.MinorLinkerVersion}"
    ts = fh.TimeDateStamp
    return {
        "kind": "DLL" if fh.Characteristics & 0x2000 else "EXE",
        "timestamp": f"0x{ts:08x} "
        + datetime.datetime.fromtimestamp(ts, datetime.UTC).strftime("%Y-%m-%d %H:%M:%S"),
        "linker": linker,
        "sections": secs,
        "compiler": compiler_guess(secs, linker, blob),
    }


def is_redist(rel: Path) -> bool:
    return any(p.lower() in REDIST_DIRS for p in rel.parts[:-1])


def walk(root: Path):
    for path in sorted(root.rglob("*")):
        if path.is_file():
            yield path


def survey() -> None:
    rows = []  # (edition, rel, size, md5, magic)
    for ed, rel_root in EDITIONS.items():
        root = REPO / rel_root
        for path in walk(root):
            rel = path.relative_to(root)
            with path.open("rb") as fh:
                head = fh.read(16)
            rows.append((ed, rel, path.stat().st_size, md5(path), magic(head), path))
        print(f"{ed}: hashed", file=sys.stderr)

    NOTES.mkdir(parents=True, exist_ok=True)
    with (NOTES / "corpus-md5.tsv").open("w", encoding="utf-8", newline="\n") as out:
        out.write("edition\tpath\tsize\tmd5\n")
        for ed, rel, size, h, _, _ in rows:
            out.write(f"{ed}\t{rel.as_posix()}\t{size}\t{h}\n")

    write_binaries(rows)
    write_inventory(rows)
    write_identical(rows)


def write_binaries(rows) -> None:
    lines = [
        "# Binaries (Ring engine corpus)",
        "",
        "Generated by `engines/ring/tools/survey.py`. Every PE file outside the DirectX",
        "redistributable folders. `crack/` files are listed only so nobody mistakes them for",
        "originals: never use them for RE.",
        "",
    ]
    redist = Counter()
    for ed in EDITIONS:
        lines += [f"## {ed} (`{EDITIONS[ed]}`)", ""]
        lines += ["| File | Size | MD5 | Kind | PE timestamp (UTC) | Compiler / linker | Sections |",
                  "|---|---:|---|---|---|---|---|"]
        for e, rel, size, h, _, path in rows:
            if e != ed or path.suffix.lower() not in PE_EXTS:
                continue
            if is_redist(rel):
                redist[ed] += 1
                continue
            info = pe_info(path)
            if info is None:
                lines.append(f"| `{rel.as_posix()}` | {size:,} | `{h}` | not MZ | | | |")
            elif "timestamp" not in info:
                lines.append(f"| `{rel.as_posix()}` | {size:,} | `{h}` | {info['kind']} | | | |")
            else:
                lines.append(
                    f"| `{rel.as_posix()}` | {size:,} | `{h}` | {info['kind']} | "
                    f"{info['timestamp']} | {info['compiler']} | {' '.join(info['sections'])} |"
                )
        lines += ["", f"DirectX redistributable PE files skipped: {redist[ed]}", ""]
    (NOTES / "binaries.md").write_text("\n".join(lines), encoding="utf-8")


def write_inventory(rows) -> None:
    lines = [
        "# Corpus inventory (Ring engine)",
        "",
        "Generated by `engines/ring/tools/survey.py`. Regenerate rather than hand-edit.",
        "Magic = first four bytes, quoted when printable, else hex. DirectX redistributables",
        "are excluded from the extension tables.",
        "",
        "| Edition | Root | Files | Bytes |",
        "|---|---|---:|---:|",
    ]
    for ed in EDITIONS:
        sel = [r for r in rows if r[0] == ed]
        lines.append(f"| {ed} | `{EDITIONS[ed]}` | {len(sel):,} | {sum(r[2] for r in sel):,} |")
    for ed in EDITIONS:
        sel = [r for r in rows if r[0] == ed and not is_redist(r[1])]
        lines += ["", f"## {ed}", "", "Layout (files per directory, two levels):", ""]
        dirs = Counter("/".join(r[1].parts[:-1][:2]) or "." for r in sel)
        for d, n in sorted(dirs.items()):
            lines.append(f"- `{d}/` {n}")
        lines += ["", "| Ext | Files | Bytes | Magics (count) |", "|---|---:|---:|---|"]
        by_ext = defaultdict(list)
        for r in sel:
            by_ext[r[1].suffix.lower() or "(none)"].append(r)
        for ext, rs in sorted(by_ext.items(), key=lambda kv: -len(kv[1])):
            mags = Counter(r[4] for r in rs)
            top = ", ".join(f"`{m}` {n}" for m, n in mags.most_common(6))
            if len(mags) > 6:
                top += f", … {len(mags)} distinct"
            lines.append(f"| `{ext}` | {len(rs):,} | {sum(r[2] for r in rs):,} | {top} |")
    (NOTES / "corpus-inventory.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


def group_of(ed: str) -> str:
    return ed.rstrip("0123456789")


def write_identical(rows) -> None:
    """Compare editions of Ring (dvd, cd, iso) on the set of file contents."""
    groups = {"ring/dvd": set(), "ring/cd": set(), "ring/iso": set(), "prophet/cd": set()}
    names = defaultdict(set)  # md5 -> {(group, lowercased path)}
    for ed, rel, _, h, _, _ in rows:
        if is_redist(rel):
            continue
        g = group_of(ed)
        groups[g].add(h)
        names[h].add((g, rel.as_posix().lower()))
    lines = [
        "# Identical files across editions",
        "",
        "Generated by `engines/ring/tools/survey.py` from `corpus-md5.tsv` (DirectX",
        "redistributables excluded). Groups: Ring DVD, Ring CD version (disc1..6), Ring ISO",
        "version (disc1..4), Prophet (cd1..2). Counts are distinct contents (MD5).",
        "",
        "| Group | Distinct contents |",
        "|---|---:|",
    ]
    for g, s in groups.items():
        lines.append(f"| {g} | {len(s):,} |")
    lines += ["", "| Shared by | Distinct contents |", "|---|---:|"]
    share = Counter()
    for h, occ in names.items():
        share[" + ".join(sorted({g for g, _ in occ}))] += 1
    for k, n in sorted(share.items(), key=lambda kv: -kv[1]):
        lines.append(f"| {k} | {n:,} |")
    # Per extension: how much of the DVD is in the CD and ISO versions.
    lines += ["", "## Ring DVD contents found in the other Ring editions, by extension", "",
              "| Ext | DVD distinct | also in CD | also in ISO | in all three |", "|---|---:|---:|---:|---:|"]
    ext_of = {}
    for ed, rel, _, h, _, _ in rows:
        if ed == "ring/dvd" and not is_redist(rel):
            ext_of[h] = rel.suffix.lower() or "(none)"
    per = defaultdict(lambda: [0, 0, 0, 0])
    for h, ext in ext_of.items():
        p = per[ext]
        p[0] += 1
        p[1] += h in groups["ring/cd"]
        p[2] += h in groups["ring/iso"]
        p[3] += h in groups["ring/cd"] and h in groups["ring/iso"]
    for ext, p in sorted(per.items(), key=lambda kv: -kv[1][0]):
        lines.append(f"| `{ext}` | {p[0]:,} | {p[1]:,} | {p[2]:,} | {p[3]:,} |")
    lines += ["", "## Files shared between Ring and Prophet", ""]
    for h, occ in sorted(names.items(), key=lambda kv: sorted(kv[1])):
        gs = {g for g, _ in occ}
        if "prophet/cd" in gs and len(gs) > 1:
            lines.append(f"- `{h}` " + ", ".join(sorted({f'{g}:{p}' for g, p in occ})))
    (NOTES / "identical-files.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


def selftest() -> None:
    assert magic(b"CNM UNR\0") == "'CNM '"
    assert magic(b"\x00\x01\x02\x03") == "00010203"
    assert group_of("ring/cd3") == "ring/cd" and group_of("ring/dvd") == "ring/dvd"
    assert group_of("ring/iso4") == "ring/iso" and group_of("prophet/cd1") == "prophet/cd"
    assert compiler_guess([".text"], "6.0", b"") == "Microsoft, linker 6.0"
    print("selftest ok")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--selftest", action="store_true")
    if ap.parse_args().selftest:
        selftest()
    else:
        survey()
