"""Write the zone set-up calls (engines/ring/notes/calls/<zone>_setup.jsonl) as the engine's
data table, ../scummvm/engines/ring/ring/setup.cpp: one {call, int arguments, strings}
entry per API call, in the binary's order, typed per zonedecl.API (spec/api.md).
Floats are kept as their 32-bit patterns.

    python engines/ring/tools/zonetable.py
    python engines/ring/tools/zonetable.py --selftest
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from zonedecl import API, CALLS, REPO  # noqa: E402

OUT = REPO.parent / "scummvm/engines/ring/ring/setup.cpp"
ZONES = ["sy", "ni", "rh", "fo", "ro", "wa", "as", "n2"]  # zone numbers 1..8 (E-0030)

HEADER = """/* ScummVM - Graphic Adventure Engine
 *
 * ScummVM is the legal property of its developers, whose names
 * are too numerous to list here. Please refer to the COPYRIGHT
 * file distributed with this source distribution.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

// Generated by engines/ring/tools/zonetable.py (research repository) from the zone
// set-up call lists of RING.EXE (DVD); the calls are described in its spec/api.md.
// Do not edit.

#include "common/util.h"

#include "ring/api.h"

namespace Ring {
"""


def c_string(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def entry(row: dict) -> str | None:
    if row["addr"] not in API:
        return None
    name, kinds = API[row["addr"]]
    ints, strs = [], []
    for value, kind in zip(row["args"], kinds):
        if kind == "s":
            ints.append(len(strs))
            strs.append(c_string(value["str"]) if isinstance(value, dict) else "nullptr")
        else:
            v = 0 if value == "?" else value & 0xFFFFFFFF
            ints.append(v - (1 << 32) if v >= 1 << 31 else v)
    enum = "k" + name.split("_")[0]
    return f"\t{{ {enum}, {len(ints)}, {{ {', '.join(map(str, ints))} }}, {{ {', '.join(strs)} }} }},"


def generate() -> tuple[str, list[str]]:
    names = sorted({n.split("_")[0] for n, _ in API.values()})
    parts = [HEADER]
    for zone in ZONES:
        rows = [json.loads(line) for line in
                (CALLS / f"{zone}_setup.jsonl").read_text(encoding="utf-8").splitlines()]
        lines = [e for e in map(entry, rows) if e]
        parts.append(f"static const SetupCall kSetup{zone.upper()}[] = {{\n" + "\n".join(lines) + "\n};\n")
    parts.append("const SetupCall *zoneSetup(int zone, uint &count) {\n\tswitch (zone) {\n" + "".join(
        f"\tcase {i + 1}: count = ARRAYSIZE(kSetup{z.upper()}); return kSetup{z.upper()};\n"
        for i, z in enumerate(ZONES)) + "\tdefault: count = 0; return nullptr;\n\t}\n}\n")
    parts.append("} // End of namespace Ring\n")
    return "\n".join(parts), names


def main() -> None:
    text, names = generate()
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print(OUT, len(text.splitlines()), "lines; enum names:", ", ".join("k" + n for n in names))


def selftest() -> None:
    row = {"addr": "00403370", "args": [90000, 0, 90000, {"str": "gm_new.bmp"}, 148, 85, 1, 1, 1000]}
    assert entry(row) == ('\t{ kObjPreAddImgToPuz, 9, { 90000, 0, 90000, 0, 148, 85, 1, 1, 1000 }, '
                          '{ "gm_new.bmp" } },'), entry(row)
    assert entry({"addr": "00405c70", "args": [1, 0x41480000, "?"]}).startswith(
        "\t{ kRotSetJugOn, 3, { 1, 1095237632, 0 }")
    assert entry({"addr": "deadbeef", "args": []}) is None
    assert c_string('a\\b"') == '"a\\\\b\\""'
    print("selftest ok")


if __name__ == "__main__":
    selftest() if "--selftest" in sys.argv else main()
