"""Render the extracted zone set-up calls (engines/ring/notes/calls/<zone>_setup.jsonl,
tools/ghidra/scripts/ring_calls.py) as readable declarations, with each argument typed
per engines/ring/docs/spec/api.md (floats shown as floats, negative ints signed).

    python engines/ring/tools/zonedecl.py            # writes engines/ring/notes/zones/<zone>.md
    python engines/ring/tools/zonedecl.py --selftest
"""

from __future__ import annotations

import json
import struct
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
CALLS = REPO / "engines/ring/notes/calls"
OUT = REPO / "engines/ring/notes/zones"

# Callee address -> (name, argument types). i int, b u8, f f32, s str. From spec/api.md.
API = {
    "00402210": ("SetZone", "b"),
    "00404240": ("AddPuz", "i"),
    "004043c0": ("PuzAddBgrImg", "isiib"),
    "00404dc0": ("AddRot", "isbi"),
    "00405fc0": ("SetComBufLen", "ii"),
    "00402900": ("AddObj", "issb"),
    "00402c40": ("ObjAddPuzAcc", "iiiiiibii"),
    "00402da0": ("ObjAddRotAcc", "iiiiiibii"),
    "00402d60": ("ObjSetPuzAccKey", "iii"),
    "00403090": ("ObjSetAccOff", "iii"),
    "004032f0": ("ObjAddPre", "i"),
    "00403370": ("ObjPreAddImgToPuz", "iiisiibbi"),
    "00403460": ("ObjPreAddAniToPuz", "iiisiiibiifb"),
    "00403560": ("ObjPreAddImgToRot", "iiii"),
    "00403660": ("ObjPreAddAniToRot", "iiiiifb"),
    "004038d0": ("ObjPreSetAniIdeOnPuz", "iiii"),
    "00403920": ("ObjPreSetAniIdeOnRot", "iiii"),
    "00403970": ("ObjPreAniSetStaFra", "iii"),
    "004039f0": ("ObjPreSetAniCooOnPuz", "iiii"),
    "00403a40": ("ObjPrePauAni", "ii"),
    "00403b10": ("ObjPreAddTxtToPuz", "iiisiiiiiiiii"),
    "00403c80": ("ObjPreSho", "i"),
    "00403e00": ("ObjPreSho", "ii"),
    "00403f80": ("ObjSetPasCur", "iiiiifii"),
    "00404030": ("ObjSetActCur", "iiiiifii"),
    "004040e0": ("ObjSetPasDraCur", "iiiiifii"),
    "00404190": ("ObjSetActDraCur", "iiiiifii"),
    "00402ed0": ("ObjAddBagAni", "iibifb"),
    "00404450": ("PuzAddMovToRot", "iisiiiibii"),
    "004046c0": ("PuzAddMovToPuz", "iisiiiibii"),
    "004050f0": ("RotAddMovToRot", "iisiiiibii"),
    "00405360": ("RotAddMovToPuz", "iisiiiibii"),
    "004045c0": ("PuzSetMovToRot", "iifff"),
    "004054b0": ("RotSetMovToPuz", "iifffib"),
    "00405250": ("RotSetMovToRot", "iifffibfff"),
    "00405850": ("RotSetMovOff", "iii"),
    "00405c70": ("RotSetJugOn", "iff"),
    "00406970": ("SouAdd", "iisiii"),
    "00406ba0": ("SouAdd", "iisi"),
    "00404b00": ("PuzAddAmbSou", "iiiiiii"),
    "00405d50": ("RotAddAmbSou", "iiiiiii"),
    "00404c30": ("PuzAdd3DSou", "iiiiiifi"),
    "00405e80": ("RotAdd3DSou", "iiiiiifi"),
    "00404be0": ("PuzSetAmbSouOff", "ii"),
    "00404d20": ("PuzSet3DSouOff", "ii"),
    "00405e30": ("RotSetAmbSouOff", "ii"),
    "00405f70": ("RotSet3DSouOff", "ii"),
    "00406e20": ("SouSet_406e20", "ii"),
    "00406080": ("VarDefByte", "ib"),
    "004060b0": ("VarSetByte", "ib"),
    "00406100": ("VarDefWord", "ii"),
    "00406180": ("VarDefDwrd", "ii"),
    "00406200": ("VarDefFloa", "if"),
    "00406280": ("VarDefStrg", "is"),
}


def fmt(value, kind: str) -> str:
    if value == "?":
        return "?"
    if isinstance(value, dict):
        return json.dumps(value["str"], ensure_ascii=False)
    if kind == "f":
        f = struct.unpack("<f", struct.pack("<I", value & 0xFFFFFFFF))[0]
        return f"{f:g}"
    if kind == "s" and value == 0:
        return "NULL"
    return str(value - (1 << 32) if value >= 1 << 31 else value)


def render(rows: list[dict]) -> list[str]:
    out = []
    for r in rows:
        name, kinds = API.get(r["addr"] or "", (r["callee"], ""))
        if r["addr"] not in API:
            out.append(f"- `{r['at']}` {name}({', '.join(str(a) for a in r['args'])}) (not an API call)")
            continue
        args = r["args"][:len(kinds)]
        out.append(f"- `{r['at']}` {name}(" + ", ".join(fmt(a, k) for a, k in zip(args, kinds)) + ")")
    return out


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    for f in sorted(CALLS.glob("*_setup.jsonl")):
        rows = [json.loads(line) for line in f.read_text(encoding="utf-8").splitlines()]
        zone = f.stem.split("_")[0]
        lines = [f"# Zone {zone.upper()} set-up (generated)", "",
                 f"Generated by `engines/ring/tools/zonedecl.py` from `notes/calls/{f.name}`;",
                 "argument types per `spec/api.md`. Do not edit.", ""] + render(rows)
        (OUT / f"{zone}.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
        print(zone, len(rows))


def selftest() -> None:
    assert fmt(0x41480000, "f") == "12.5"
    assert fmt(4294967225, "i") == "-71"
    assert fmt({"str": "a.bma"}, "s") == '"a.bma"'
    row = {"at": "1", "addr": "004045c0", "callee": "x", "args": [5, 0, 0x42500000, 0, 0x42aa999a]}
    assert render([row])[0].endswith("PuzSetMovToRot(5, 0, 52, 0, 85.3)"), render([row])
    print("selftest ok")


if __name__ == "__main__":
    selftest() if "--selftest" in sys.argv else main()
