"""Generate the x3d.dll / h3d.dll tracing proxies from the real export tables.

The proxy exports every symbol the original DLL does, logs each call, and tail-jumps to
the real implementation. It is the behavioural oracle: when static analysis and a trace
disagree, the trace wins (CLAUDE.md).

Signatures are unknown at this stage, so the thunks are `__declspec(naked)` and never
touch the argument area. Each one saves all registers and flags, calls the logger,
restores them, and jumps — not calls — the real function, which then returns straight to
the original caller and cleans the stack according to its own convention. That is correct
for `__cdecl`, `__stdcall`, `__thiscall` and `__fastcall` alike without knowing which is
in use. EAX is the only register the jump could disturb, and no x86 convention passes an
argument in EAX.

The return address is captured at each call site: it identifies the calling function,
which joins straight back to `notes/function-map.csv`.

    python tools/proxy/gen_proxy.py            # regenerate tools/proxy/generated/
    python tools/proxy/gen_proxy.py --selftest

Deployment: build, rename the game's `x3d.dll` to `x3d_orig.dll`, drop the proxy in as
`x3d.dll`. Never modify the originals in place (CLAUDE.md rule 7) — copy the install
directory first.
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
BIN_DIR = REPO / "Original Game Files" / "INSTALL" / "02_PR"
OUT_DIR = Path(__file__).resolve().parent / "generated"

# Proxied DLL -> the name the original must be renamed to.
TARGETS = {"x3d.dll": "x3d_orig.dll", "h3d.dll": "h3d_orig.dll"}

C_HEADER = r"""/* Generated by tools/proxy/gen_proxy.py. Do not edit; regenerate. */
#include <windows.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define REAL_DLL   "%(real_dll)s"
#define PROXY_NAME "%(proxy_name)s"
#define EXPORT_COUNT %(count)d

static FARPROC           g_real[EXPORT_COUNT];
static const char *const g_names[EXPORT_COUNT] = {
%(names)s};

static FILE            *g_log;
static CRITICAL_SECTION g_lock;
static LONG             g_seq;
static double           g_ms_per_tick;
static DWORD            g_last_flush;
/* Frame mode (default). A frame ends at a boundary export (X3d_Render in x3d.dll,
   H3d_Show_BackBuffer in h3d.dll). Within a frame each (export, call site) pair is written
   once, in order of first call, with " xN" for its count; the seq and t= are those of the
   first call. A frame whose list of (export, call site) pairs equals the previous frame's
   is not written: "= xN" counts such frames. This keeps per-face collision loops and
   uncapped frame rates (~240 fps windowed) to a few lines per distinct frame.
   MONET_TRACE_RAW=1: one line per run of identical consecutive calls instead. */
#define FRAME_MAX 512
typedef struct { int index; void *ret; LONG seq; LONGLONG tick; LONG count; } entry_t;
static entry_t          g_frame[FRAME_MAX], g_prev[FRAME_MAX];
static int              g_frame_n, g_prev_n;
static LONG             g_same_frames;
static int              g_raw;
static int              g_boundary = -1;

/* Resolve REAL_DLL next to this proxy rather than by search order: the proxy carries the
   same name as the DLL it replaces, so a bare LoadLibrary risks finding itself. */
static HMODULE load_real(HINSTANCE self)
{
    char path[MAX_PATH];
    DWORD n = GetModuleFileNameA(self, path, MAX_PATH);
    while (n > 0 && path[n - 1] != '\\' && path[n - 1] != '/')
        n--;
    path[n] = 0;
    if (n + sizeof(REAL_DLL) > MAX_PATH)
        return NULL;
    memcpy(path + n, REAL_DLL, sizeof(REAL_DLL));
    return LoadLibraryA(path);
}

static void open_log(void)
{
    const char *env = getenv("MONET_TRACE");
    char name[MAX_PATH];
    if (env && *env) {
        g_log = fopen(env, "w");
    } else {
        _snprintf(name, sizeof(name), "monet-trace-%%s-%%lu.log", PROXY_NAME,
                  (unsigned long)GetCurrentProcessId());
        name[sizeof(name) - 1] = 0;
        g_log = fopen(name, "w");
    }
    if (g_log)
        fprintf(g_log, "# monet proxy trace: %%s, %%d exports\n", PROXY_NAME,
                EXPORT_COUNT);
}

/* Caller holds g_lock. Time is QueryPerformanceCounter in ms, a machine-wide clock, so
   the x3d and h3d traces of one run can be merged by it. */
static void write_entry(const entry_t *e)
{
    fprintf(g_log, "%%ld t=%%.3f %%s!%%s ret=0x%%08lx", (long)e->seq,
            (double)e->tick * g_ms_per_tick, PROXY_NAME, g_names[e->index],
            (unsigned long)(UINT_PTR)e->ret);
    if (e->count > 1)
        fprintf(g_log, " x%%ld", (long)e->count);
    fputc('\n', g_log);
}

static void flush_same(void)
{
    if (g_same_frames) {
        fprintf(g_log, "= x%%ld\n", (long)g_same_frames);
        g_same_frames = 0;
    }
}

/* Caller holds g_lock. */
static void end_frame(void)
{
    int i, same = g_frame_n > 0 && g_frame_n == g_prev_n;
    for (i = 0; same && i < g_frame_n; i++)
        same = g_frame[i].index == g_prev[i].index && g_frame[i].ret == g_prev[i].ret;
    if (same) {
        g_same_frames++;
    } else {
        flush_same();
        for (i = 0; i < g_frame_n; i++)
            write_entry(&g_frame[i]);
        memcpy(g_prev, g_frame, sizeof(entry_t) * g_frame_n);
        g_prev_n = g_frame_n;
    }
    g_frame_n = 0;
}

/* Caller holds g_lock. Written at DLL_PROCESS_DETACH. */
static void flush_all(void)
{
    if (g_raw) {
        if (g_frame_n)
            write_entry(&g_frame[0]);
        g_frame_n = 0;
    } else {
        end_frame();
        flush_same();
    }
}

/* __cdecl: the thunk cleans up its own two arguments. */
void log_entry(int index, void *ret_addr)
{
    LONG seq = InterlockedIncrement(&g_seq);
    LARGE_INTEGER now;
    DWORD tick;
    int i;
    if (!g_log)
        return;
    EnterCriticalSection(&g_lock);
    if (g_raw) {
        if (g_frame_n && g_frame[0].index == index && g_frame[0].ret == ret_addr) {
            g_frame[0].count++;
        } else {
            if (g_frame_n)
                write_entry(&g_frame[0]);
            QueryPerformanceCounter(&now);
            g_frame[0].index = index; g_frame[0].ret = ret_addr; g_frame[0].seq = seq;
            g_frame[0].tick = now.QuadPart; g_frame[0].count = 1;
            g_frame_n = 1;
        }
    } else {
        for (i = g_frame_n - 1; i >= 0; i--)
            if (g_frame[i].index == index && g_frame[i].ret == ret_addr)
                break;
        if (i >= 0) {
            g_frame[i].count++;
        } else {
            if (g_frame_n == FRAME_MAX)
                end_frame();
            QueryPerformanceCounter(&now);
            i = g_frame_n++;
            g_frame[i].index = index; g_frame[i].ret = ret_addr; g_frame[i].seq = seq;
            g_frame[i].tick = now.QuadPart; g_frame[i].count = 1;
        }
        if (index == g_boundary)
            end_frame();
    }
    /* A killed process never reaches DLL_PROCESS_DETACH; lose at most ~1 s of trace. */
    tick = GetTickCount();
    if (tick - g_last_flush > 1000) {
        fflush(g_log);
        g_last_flush = tick;
    }
    LeaveCriticalSection(&g_lock);
}

/* An unresolved export must be loud rather than a wild jump through a null pointer. */
void missing_export(int index)
{
    char msg[256];
    _snprintf(msg, sizeof(msg), "%%s: export %%s missing from " REAL_DLL, PROXY_NAME,
              g_names[index]);
    msg[sizeof(msg) - 1] = 0;
    if (g_log) {
        fprintf(g_log, "# FATAL %%s\n", msg);
        fflush(g_log);
    }
    MessageBoxA(NULL, msg, "monet proxy", MB_OK | MB_ICONERROR);
    ExitProcess(1);
}

/* Background mode (MONET_BACKGROUND=1): the game offers every window message to
   H3d_WindowProc first and skips its own handling when that reports "handled"
   (MissionMonet.exe 0x004166d5, out-params are the last two arguments). The game's own
   handler clears its "active" flag on focus loss and the main loop stalls until it is
   set again, so swallowing focus-loss messages here lets it keep running behind other
   windows. Off by default: it changes behaviour, and the trace header says when it is on. */
typedef int (__cdecl *h3d_wndproc_t)(void *, HWND, UINT, WPARAM, LPARAM, int *, LRESULT *);
static h3d_wndproc_t g_real_wndproc;

/* Background mode also lets posted keys reach GetAsyncKeyState. Videos and scripted waits
   poll the physical key state (Enter/Escape, E-0043), which posted WM_KEYDOWNs never set,
   so a test driver could not skip them. The exe's GetAsyncKeyState import is redirected
   to report a key as down while a posted WM_KEYDOWN has not been followed by WM_KEYUP. */
static volatile LONG g_posted_down[256];
static SHORT (WINAPI *g_real_gaks)(int);

static SHORT WINAPI background_gaks(int vk)
{
    SHORT real = g_real_gaks(vk);
    return (vk >= 0 && vk < 256 && g_posted_down[vk]) ? (SHORT)(real | 0x8000) : real;
}

/* Rewrites the exe's IAT slot. Done on the first window message, when the exe's imports
   are certainly bound. */
static void hook_get_async_key_state(void)
{
    BYTE *base = (BYTE *)GetModuleHandleA(NULL);
    IMAGE_NT_HEADERS *nt = (IMAGE_NT_HEADERS *)(base + ((IMAGE_DOS_HEADER *)base)->e_lfanew);
    IMAGE_DATA_DIRECTORY dir = nt->OptionalHeader.DataDirectory[IMAGE_DIRECTORY_ENTRY_IMPORT];
    IMAGE_IMPORT_DESCRIPTOR *d = (IMAGE_IMPORT_DESCRIPTOR *)(base + dir.VirtualAddress);
    FARPROC target = GetProcAddress(GetModuleHandleA("user32.dll"), "GetAsyncKeyState");

    for (; d->Name; d++) {
        IMAGE_THUNK_DATA *t = (IMAGE_THUNK_DATA *)(base + d->FirstThunk);
        for (; t->u1.Function; t++) {
            if ((FARPROC)t->u1.Function == target) {
                DWORD old;
                VirtualProtect(&t->u1.Function, sizeof(t->u1.Function), PAGE_READWRITE, &old);
                g_real_gaks = (SHORT (WINAPI *)(int))target;
                t->u1.Function = (DWORD)(DWORD_PTR)background_gaks;
                VirtualProtect(&t->u1.Function, sizeof(t->u1.Function), old, &old);
                if (g_log)
                    fprintf(g_log, "# background mode: posted keys reach GetAsyncKeyState\n");
                return;
            }
        }
    }
}

static int __cdecl background_wndproc(void *ctx, HWND hwnd, UINT msg, WPARAM wp, LPARAM lp,
                                      int *handled, LRESULT *result)
{
    static int hooked;
    if (!hooked) {
        hooked = 1;
        hook_get_async_key_state();
    }
    if ((msg == WM_KEYDOWN || msg == WM_KEYUP) && wp < 256)
        g_posted_down[wp] = (msg == WM_KEYDOWN);
    if ((msg == WM_ACTIVATEAPP && !wp) || (msg == WM_ACTIVATE && LOWORD(wp) == WA_INACTIVE)) {
        *handled = 1;
        *result = 0;
        return 1;
    }
    return g_real_wndproc(ctx, hwnd, msg, wp, lp, handled, result);
}

BOOL WINAPI DllMain(HINSTANCE self, DWORD reason, LPVOID reserved)
{
    int i;
    HMODULE real;

    (void)reserved;
    switch (reason) {
    case DLL_PROCESS_ATTACH:
        DisableThreadLibraryCalls(self);
        InitializeCriticalSection(&g_lock);
        {
            LARGE_INTEGER f;
            QueryPerformanceFrequency(&f);
            g_ms_per_tick = 1000.0 / (double)f.QuadPart;
        }
        open_log();
        real = load_real(self);
        if (!real) {
            MessageBoxA(NULL, "cannot load " REAL_DLL, "monet proxy",
                        MB_OK | MB_ICONERROR);
            return FALSE;
        }
        g_raw = getenv("MONET_TRACE_RAW") && *getenv("MONET_TRACE_RAW") == '1';
        for (i = 0; i < EXPORT_COUNT; i++) {
            g_real[i] = GetProcAddress(real, g_names[i]);
            if (strcmp(g_names[i], "X3d_Render") == 0 || strcmp(g_names[i], "H3d_Show_BackBuffer") == 0)
                g_boundary = i;
            if (strcmp(g_names[i], "H3d_WindowProc") == 0 && g_real[i]
                && getenv("MONET_BACKGROUND") && *getenv("MONET_BACKGROUND") == '1') {
                g_real_wndproc = (h3d_wndproc_t)g_real[i];
                g_real[i] = (FARPROC)background_wndproc;
                if (g_log)
                    fprintf(g_log, "# background mode: focus-loss messages swallowed\n");
            }
        }
        if (g_log)
            fprintf(g_log, "# mode: %%s%%s\n", g_raw ? "raw" : "frames, boundary ",
                    g_raw ? "" : (g_boundary >= 0 ? g_names[g_boundary] : "none"));
        break;
    case DLL_PROCESS_DETACH:
        if (g_log) {
            EnterCriticalSection(&g_lock);
            flush_all();
            LeaveCriticalSection(&g_lock);
            fprintf(g_log, "# %%ld calls\n", (long)g_seq);
            fclose(g_log);
            g_log = NULL;
        }
        DeleteCriticalSection(&g_lock);
        break;
    }
    return TRUE;
}
"""

# One thunk per export. `pushad`/`popad` and `pushfd`/`popfd` bracket the logging call so
# the callee sees exactly the register state the caller set up. Inside them the return
# address sits 36 bytes up the stack: 32 for pushad, 4 for pushfd.
STUB = r"""
__declspec(naked) void stub_%(index)d(void)
{
    __asm {
        pushad
        pushfd
        push dword ptr [esp + 36]
        push %(index)d
        call log_entry
        add  esp, 8
        cmp  dword ptr [g_real + %(offset)d], 0
        je   no_target
        popfd
        popad
        jmp  dword ptr [g_real + %(offset)d]
    no_target:
        popfd
        popad
        push %(index)d
        call missing_export
    }
}
"""


def exports(dll: Path) -> list:
    """(ordinal, name, is_data) for every export, in ordinal order.

    x3d.dll exports its math function pointers (`X3d_Matrice_Mult`, ...) as variables in
    .data; the game calls through them (`call [iat_value]`). A code stub in their place
    made the game jump through the stub's bytes ~1.5 s into U01, so data exports are
    forwarded to the real DLL instead of traced."""
    import pefile

    pe = pefile.PE(str(dll))
    out = []
    for sym in pe.DIRECTORY_ENTRY_EXPORT.symbols:
        if not sym.name:
            raise SystemExit(
                "%s exports by ordinal only; the generator assumes names" % dll.name
            )
        if sym.forwarder:
            raise SystemExit("%s has forwarder exports; not handled" % dll.name)
        section = pe.get_section_by_rva(sym.address)
        is_data = not (section.Characteristics & 0x20000000)  # IMAGE_SCN_MEM_EXECUTE
        out.append((sym.ordinal, sym.name.decode("ascii"), is_data))
    return sorted(out)


def render_c(proxy_name: str, real_dll: str, names: list, forwards: list = ()) -> str:
    body = C_HEADER % {
        "real_dll": real_dll,
        "proxy_name": proxy_name,
        "count": len(names),
        "names": "".join('    "%s",\n' % n for n in names),
    }
    body += "".join(
        '#pragma comment(linker, "/export:%s=%s.%s,@%d")\n' % (n, real_dll[: -len(".dll")], n, o)
        for o, n in forwards
    )
    stubs = "".join(STUB % {"index": i, "offset": i * 4} for i in range(len(names)))
    return body + stubs


def render_def(syms: list, real_dll: str) -> str:
    lines = ["EXPORTS"]
    for index, (ordinal, name, is_data) in enumerate(syms):
        # Ordinals are preserved: the EXEs import by name, but nothing guarantees the
        # other engine DLLs do.
        # Data exports are forwarded by render_c's /export pragmas: link.exe rejects
        # forwarders in this .def (LNK2001).
        if not is_data:
            lines.append("    %s=stub_%d @%d" % (name, index, ordinal))
    return "\n".join(lines) + "\n"


def generate(out_dir: Path) -> dict:
    out_dir.mkdir(parents=True, exist_ok=True)
    written = {}
    for proxy_dll, real_dll in sorted(TARGETS.items()):
        stem = proxy_dll[: -len(".dll")]
        syms = exports(BIN_DIR / proxy_dll)
        names = [n for _, n, _ in syms]
        (out_dir / (stem + "_proxy.c")).write_text(
            render_c(proxy_dll, real_dll, names, [(o, n) for o, n, d in syms if d]),
            encoding="ascii",
        )
        (out_dir / (stem + ".def")).write_text(render_def(syms, real_dll), encoding="ascii")
        written[proxy_dll] = len(names)
        print(
            "%s: %d exports -> %s_proxy.c, %s.def" % (proxy_dll, len(names), stem, stem)
        )
    return written


def selftest() -> int:
    import tempfile

    syms = [(1, "X3d_Alpha", False), (2, "X3d_Beta", True), (3, "X3d_Gamma", False)]
    d = render_def(syms, "x3d_orig.dll")
    assert d.splitlines()[0] == "EXPORTS"
    assert "    X3d_Alpha=stub_0 @1" in d
    assert "    X3d_Gamma=stub_2 @3" in d
    assert "X3d_Beta" not in d
    assert len(d.strip().splitlines()) == len(syms)  # header, minus the data export

    c = render_c("x3d.dll", "x3d_orig.dll", [n for _, n, _ in syms])
    assert c.count("__declspec(naked)") == 3
    assert "#define EXPORT_COUNT 3" in c
    assert '"X3d_Beta",' in c
    # The third stub must index the third slot of the pointer table, not the first.
    assert "cmp  dword ptr [g_real + 8], 0" in c
    assert "push 2\n        call log_entry" in c
    # No stray escaping survived the two-stage % formatting.
    assert "%%" not in c, "double-percent leaked into the generated C"
    assert 'fprintf(g_log, "%ld t=%.3f %s!%s ret=0x%08lx"' in c

    with tempfile.TemporaryDirectory() as tmp:
        out = Path(tmp)
        if BIN_DIR.is_dir():
            counts = generate(out)
            assert counts == {"x3d.dll": 278, "h3d.dll": 52}, counts
            body = (out / "x3d.def").read_text(encoding="ascii")
            assert len(body.strip().splitlines()) == 279 - 32  # data exports forwarded
            c_body = (out / "x3d_proxy.c").read_text(encoding="ascii")
            assert "/export:X3d_Matrice_Mult=x3d_orig.X3d_Matrice_Mult,@" in c_body
        else:
            print("  (binaries absent; skipped the end-to-end generation check)")
    print("selftest ok")
    return 0


def main(argv: list) -> int:
    if "--selftest" in argv:
        return selftest()
    generate(OUT_DIR)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
