"""Generate the x3d.dll / h3d.dll tracing proxies from the real export tables.

The proxy exports every symbol the original DLL does, logs each call, and tail-jumps to
the real implementation. It is the behavioural oracle: when static analysis and a trace
disagree, the trace wins (CLAUDE.md).

Signatures are unknown at this stage, so the thunks are `__declspec(naked)` and never
touch the argument area. Each one saves all registers and flags, calls the logger,
restores them, and jumps — not calls — the real function, which then returns straight to
the original caller and cleans the stack according to its own convention. That is correct
for `__cdecl`, `__stdcall`, `__thiscall` and `__fastcall` alike without knowing which is
in use. EAX is the only register the jump could disturb, and no x86 convention passes an
argument in EAX.

The return address is captured at each call site: it identifies the calling function,
which joins straight back to `notes/function-map.csv`.

    python tools/proxy/gen_proxy.py            # regenerate tools/proxy/generated/
    python tools/proxy/gen_proxy.py --selftest

Deployment: build, rename the game's `x3d.dll` to `x3d_orig.dll`, drop the proxy in as
`x3d.dll`. Never modify the originals in place (CLAUDE.md rule 7) — copy the install
directory first.
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
BIN_DIR = REPO / "Original Game Files" / "INSTALL" / "02_PR"
OUT_DIR = Path(__file__).resolve().parent / "generated"

# Proxied DLL -> the name the original must be renamed to.
TARGETS = {"x3d.dll": "x3d_orig.dll", "h3d.dll": "h3d_orig.dll"}

C_HEADER = r"""/* Generated by tools/proxy/gen_proxy.py. Do not edit; regenerate. */
#include <windows.h>
#include <stdio.h>
#include <stdlib.h>

#define REAL_DLL   "%(real_dll)s"
#define PROXY_NAME "%(proxy_name)s"
#define EXPORT_COUNT %(count)d

static FARPROC           g_real[EXPORT_COUNT];
static const char *const g_names[EXPORT_COUNT] = {
%(names)s};

static FILE            *g_log;
static CRITICAL_SECTION g_lock;
static LONG             g_seq;

/* Resolve REAL_DLL next to this proxy rather than by search order: the proxy carries the
   same name as the DLL it replaces, so a bare LoadLibrary risks finding itself. */
static HMODULE load_real(HINSTANCE self)
{
    char path[MAX_PATH];
    DWORD n = GetModuleFileNameA(self, path, MAX_PATH);
    while (n > 0 && path[n - 1] != '\\' && path[n - 1] != '/')
        n--;
    path[n] = 0;
    if (n + sizeof(REAL_DLL) > MAX_PATH)
        return NULL;
    memcpy(path + n, REAL_DLL, sizeof(REAL_DLL));
    return LoadLibraryA(path);
}

static void open_log(void)
{
    const char *env = getenv("MONET_TRACE");
    char name[MAX_PATH];
    if (env && *env) {
        g_log = fopen(env, "w");
    } else {
        _snprintf(name, sizeof(name), "monet-trace-%%s-%%lu.log", PROXY_NAME,
                  (unsigned long)GetCurrentProcessId());
        name[sizeof(name) - 1] = 0;
        g_log = fopen(name, "w");
    }
    if (g_log)
        fprintf(g_log, "# monet proxy trace: %%s, %%d exports\n", PROXY_NAME,
                EXPORT_COUNT);
}

/* __cdecl: the thunk cleans up its own two arguments. */
void log_entry(int index, void *ret_addr)
{
    LONG seq = InterlockedIncrement(&g_seq);
    if (!g_log)
        return;
    EnterCriticalSection(&g_lock);
    fprintf(g_log, "%%ld %%s!%%s ret=0x%%08lx\n", (long)seq, PROXY_NAME,
            g_names[index], (unsigned long)(UINT_PTR)ret_addr);
    LeaveCriticalSection(&g_lock);
}

/* An unresolved export must be loud rather than a wild jump through a null pointer. */
void missing_export(int index)
{
    char msg[256];
    _snprintf(msg, sizeof(msg), "%%s: export %%s missing from " REAL_DLL, PROXY_NAME,
              g_names[index]);
    msg[sizeof(msg) - 1] = 0;
    if (g_log) {
        fprintf(g_log, "# FATAL %%s\n", msg);
        fflush(g_log);
    }
    MessageBoxA(NULL, msg, "monet proxy", MB_OK | MB_ICONERROR);
    ExitProcess(1);
}

BOOL WINAPI DllMain(HINSTANCE self, DWORD reason, LPVOID reserved)
{
    int i;
    HMODULE real;

    (void)reserved;
    switch (reason) {
    case DLL_PROCESS_ATTACH:
        DisableThreadLibraryCalls(self);
        InitializeCriticalSection(&g_lock);
        open_log();
        real = load_real(self);
        if (!real) {
            MessageBoxA(NULL, "cannot load " REAL_DLL, "monet proxy",
                        MB_OK | MB_ICONERROR);
            return FALSE;
        }
        for (i = 0; i < EXPORT_COUNT; i++)
            g_real[i] = GetProcAddress(real, g_names[i]);
        break;
    case DLL_PROCESS_DETACH:
        if (g_log) {
            fprintf(g_log, "# %%ld calls\n", (long)g_seq);
            fclose(g_log);
            g_log = NULL;
        }
        DeleteCriticalSection(&g_lock);
        break;
    }
    return TRUE;
}
"""

# One thunk per export. `pushad`/`popad` and `pushfd`/`popfd` bracket the logging call so
# the callee sees exactly the register state the caller set up. Inside them the return
# address sits 36 bytes up the stack: 32 for pushad, 4 for pushfd.
STUB = r"""
__declspec(naked) void stub_%(index)d(void)
{
    __asm {
        pushad
        pushfd
        push dword ptr [esp + 36]
        push %(index)d
        call log_entry
        add  esp, 8
        cmp  dword ptr [g_real + %(offset)d], 0
        je   no_target
        popfd
        popad
        jmp  dword ptr [g_real + %(offset)d]
    no_target:
        popfd
        popad
        push %(index)d
        call missing_export
    }
}
"""


def exports(dll: Path) -> list:
    """(ordinal, name) for every export, in ordinal order."""
    import pefile

    pe = pefile.PE(str(dll))
    out = []
    for sym in pe.DIRECTORY_ENTRY_EXPORT.symbols:
        if not sym.name:
            raise SystemExit(
                "%s exports by ordinal only; the generator assumes names" % dll.name
            )
        if sym.forwarder:
            raise SystemExit("%s has forwarder exports; not handled" % dll.name)
        out.append((sym.ordinal, sym.name.decode("ascii")))
    return sorted(out)


def render_c(proxy_name: str, real_dll: str, names: list) -> str:
    body = C_HEADER % {
        "real_dll": real_dll,
        "proxy_name": proxy_name,
        "count": len(names),
        "names": "".join('    "%s",\n' % n for n in names),
    }
    stubs = "".join(STUB % {"index": i, "offset": i * 4} for i in range(len(names)))
    return body + stubs


def render_def(names_with_ordinals: list) -> str:
    lines = ["EXPORTS"]
    for index, (ordinal, name) in enumerate(names_with_ordinals):
        # Ordinals are preserved: the EXEs import by name, but nothing guarantees the
        # other engine DLLs do.
        lines.append("    %s=stub_%d @%d" % (name, index, ordinal))
    return "\n".join(lines) + "\n"


def generate(out_dir: Path) -> dict:
    out_dir.mkdir(parents=True, exist_ok=True)
    written = {}
    for proxy_dll, real_dll in sorted(TARGETS.items()):
        stem = proxy_dll[: -len(".dll")]
        syms = exports(BIN_DIR / proxy_dll)
        names = [n for _, n in syms]
        (out_dir / (stem + "_proxy.c")).write_text(
            render_c(proxy_dll, real_dll, names), encoding="ascii"
        )
        (out_dir / (stem + ".def")).write_text(render_def(syms), encoding="ascii")
        written[proxy_dll] = len(names)
        print(
            "%s: %d exports -> %s_proxy.c, %s.def" % (proxy_dll, len(names), stem, stem)
        )
    return written


def selftest() -> int:
    import tempfile

    syms = [(1, "X3d_Alpha"), (2, "X3d_Beta"), (3, "X3d_Gamma")]
    d = render_def(syms)
    assert d.splitlines()[0] == "EXPORTS"
    assert "    X3d_Alpha=stub_0 @1" in d
    assert "    X3d_Gamma=stub_2 @3" in d
    assert len(d.strip().splitlines()) == len(syms) + 1

    c = render_c("x3d.dll", "x3d_orig.dll", [n for _, n in syms])
    assert c.count("__declspec(naked)") == 3
    assert "#define EXPORT_COUNT 3" in c
    assert '"X3d_Beta",' in c
    # The third stub must index the third slot of the pointer table, not the first.
    assert "cmp  dword ptr [g_real + 8], 0" in c
    assert "push 2\n        call log_entry" in c
    # No stray escaping survived the two-stage % formatting.
    assert "%%" not in c, "double-percent leaked into the generated C"
    assert 'fprintf(g_log, "%ld %s!%s ret=0x%08lx\\n"' in c

    with tempfile.TemporaryDirectory() as tmp:
        out = Path(tmp)
        if BIN_DIR.is_dir():
            counts = generate(out)
            assert counts == {"x3d.dll": 278, "h3d.dll": 52}, counts
            body = (out / "x3d.def").read_text(encoding="ascii")
            assert len(body.strip().splitlines()) == 279
        else:
            print("  (binaries absent; skipped the end-to-end generation check)")
    print("selftest ok")
    return 0


def main(argv: list) -> int:
    if "--selftest" in argv:
        return selftest()
    generate(OUT_DIR)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
