"""Find the virtual-method tables of a Ring-engine EXE and attach class names to them.

No RTTI in these builds (engines/ring E-0002). A vtable is found the way a constructor
installs it: `MOV dword ptr [reg(+0)], imm32` where imm32 points into a non-executable block
and the dwords there are, one after another, entry points of functions. The table ends at
the first dword that is not a function entry, or where another table starts.

A table gets a class name only when every entry and every writer (constructor,
destructor) already carrying a class namespace (ring_string_namer.py) agrees; the rest are listed unnamed. Writers of the table (the
constructors and destructors) are listed with it. Labels `vftable_<Class>` (or
`vftable_<addr>`) are created; functions are not renamed.

    python -m pyghidra.ghidra_launch --install-dir 'C:\\ghidra' \\
        ghidra.app.util.headless.AnalyzeHeadless ghidra_projects Ring \\
        -process RING_DVD.EXE -noanalysis \\
        -scriptPath tools/ghidra/scripts -postScript ring_vtables.py engines/ring/notes/vtables

Self-check (plain CPython): python tools/ghidra/scripts/ring_vtables.py --selftest
"""

from __future__ import annotations

import sys
from collections import Counter, defaultdict
from pathlib import Path


def cut_tables(starts: list[int], length_of) -> dict[int, int]:
    """Entry counts per table start: a table runs until its own end or the next start."""
    out = {}
    starts = sorted(set(starts))
    for i, s in enumerate(starts):
        limit = (starts[i + 1] - s) // 4 if i + 1 < len(starts) else 1 << 20
        out[s] = min(length_of(s), limit)
    return {s: n for s, n in out.items() if n > 0}


def class_of(names: list[str]) -> str | None:
    """The one class every namespaced entry agrees on, else None."""
    classes = {n.split("::")[0] for n in names if "::" in n}
    return classes.pop() if len(classes) == 1 else None


def scan(program, out_dir: Path) -> None:
    from ghidra.program.model.symbol import SourceType
    from ghidra.program.model.scalar import Scalar

    listing = program.getListing()
    mem = program.getMemory()
    fm = program.getFunctionManager()
    space = program.getAddressFactory().getDefaultAddressSpace()

    def data_addr(value: int) -> bool:
        b = mem.getBlock(space.getAddress(value)) if 0 <= value < (1 << 32) else None
        return b is not None and b.isInitialized() and not b.isExecute()

    def func_at(value: int):
        try:
            return fm.getFunctionAt(space.getAddress(value))
        except Exception:
            return None

    def dword(value: int) -> int:
        return mem.getInt(space.getAddress(value)) & 0xFFFFFFFF

    writers = defaultdict(set)
    for ins in listing.getInstructions(True):
        if ins.getMnemonicString() != "MOV" or ins.getNumOperands() != 2:
            continue
        objs = ins.getOpObjects(1)
        if len(objs) != 1 or not isinstance(objs[0], Scalar):
            continue
        dst = ins.getDefaultOperandRepresentation(0)
        if not dst.startswith("dword ptr [") or "+" in dst or "-" in dst:
            continue  # only stores to offset 0 of an object
        value = objs[0].getUnsignedValue()
        if not data_addr(value) or func_at(dword(value)) is None:
            continue
        f = listing.getFunctionContaining(ins.getAddress())
        writers[value].add(str(f.getEntryPoint()) + " " + f.getName(True) if f else str(ins.getAddress()))

    def length_of(start: int) -> int:
        n = 0
        while func_at(dword(start + 4 * n)) is not None:
            n += 1
        return n

    tables = cut_tables(list(writers), length_of)
    lines = [f"# vtables of {program.getName()}", "",
             "Generated by `tools/ghidra/scripts/ring_vtables.py`. A class name means every",
             "entry and writer named by `ring_string_namer.py` carries that class.", ""]
    named = 0
    for start, count in sorted(tables.items()):
        entries = [func_at(dword(start + 4 * i)) for i in range(count)]
        names = [e.getName(True) for e in entries]
        cls = class_of(names + [w.split(" ", 1)[1] for w in writers[start]])
        named += cls is not None
        label = f"vftable_{cls}" if cls else f"vftable_{start:08x}"
        try:
            program.getSymbolTable().createLabel(space.getAddress(start), label, SourceType.ANALYSIS)
        except Exception as exc:
            print(f"  label failed at {start:08x}: {exc}")
        lines += [f"## `{start:08x}` {cls or '(unnamed)'}: {count} entries", "",
                  "Written by: " + ", ".join(f"`{w}`" for w in sorted(writers[start])), ""]
        lines += [f"{i:3d} `{e.getEntryPoint()}` {n}" for i, (e, n) in enumerate(zip(entries, names))]
        lines.append("")
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / f"{program.getName()}.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"{program.getName()}: {len(tables)} vtables, {named} with a class name")


def selftest() -> None:
    lengths = {0x100: 5, 0x10c: 2, 0x200: 3}
    assert cut_tables([0x10c, 0x100, 0x200], lengths.get) == {0x100: 3, 0x10c: 2, 0x200: 3}
    assert class_of(["aImage::Load", "FUN_1", "aImage::Save"]) == "aImage"
    assert class_of(["aImage::Load", "aCin::Init"]) is None
    assert class_of(["FUN_1"]) is None
    print("selftest ok")


if "--selftest" in sys.argv:
    selftest()
else:
    args = getScriptArgs()  # noqa: F821 (Ghidra script global)
    scan(currentProgram, Path(args[0] if args else "engines/ring/notes/vtables"))  # noqa: F821
