"""Survey the Grumpa corpus (engine `grumpa`).

Read-only over games/grumpa/discs/{cd,cab}: `cd` is the ISO's file system, `cab` the
InstallShield cabinet `data1.hdr`/`data2.cab` unpacked by file group with unshield
(`third_party/unshield`, see E-0001). Writes into engines/grumpa/notes/:

  binaries.md         every PE file: MD5, size, PE timestamp, linker, Rich header,
                      sections with entropy, imports, exports, SafeDisc version block.
                      Redistributables (DirectX 8, MFC runtime, InstallShield engine and
                      support files) only counted.
  corpus-inventory.md layout, then extension x magic counts.
  corpus-md5.tsv      path, size, MD5 of every file.

    python engines/grumpa/tools/survey.py
    python engines/grumpa/tools/survey.py --selftest
"""

from __future__ import annotations

import argparse
import datetime
import hashlib
import math
import struct
from collections import Counter, defaultdict
from pathlib import Path

import pefile

REPO = Path(__file__).resolve().parents[3]
NOTES = REPO / "engines/grumpa/notes"
DISCS = REPO / "games/grumpa/discs"
ROOTS = ("cd", "cab")
PE_EXTS = {".exe", ".dll", ".sys"}
# SafeDisc's marker; three u32 (major, minor, build) follow 16 bytes after it.
BOG = b"BoG_ *90.0&!!  Yy>"


def md5(path: Path) -> str:
    return hashlib.md5(path.read_bytes()).hexdigest()


def magic(head: bytes) -> str:
    """First four bytes as text when printable, else hex."""
    m = head[:4]
    if len(m) == 4 and all(32 <= b < 127 for b in m):
        return "'" + m.decode() + "'"
    return m.hex()


def is_redist(rel: Path) -> bool:
    """rel is relative to DISCS: cd/DIRECTX8, cab/_MFC_*, cab/_Support_*, cab/_Engine_*."""
    p = rel.parts
    return (p[0] == "cd" and len(p) > 2 and p[1] == "DIRECTX8") or (
        p[0] == "cab" and len(p) > 2 and p[1].startswith(("_MFC_", "_Support_", "_Engine_")))


def entropy(data: bytes) -> float:
    if not data:
        return 0.0
    n = len(data)
    return -sum(c / n * math.log2(c / n) for c in Counter(data).values())


def safedisc(blob: bytes) -> str | None:
    i = blob.find(BOG)
    if i < 0:
        return None
    major, minor, build = struct.unpack_from("<3I", blob, i + 32)
    return f"{major}.{minor:02d}.{build:03d} (marker at file offset 0x{i:x})"


def rich(pe) -> str:
    rh = pe.parse_rich_header()
    if not rh:
        return "none"
    v = rh["values"]
    return ", ".join(f"id {v[i] >> 16} build {v[i] & 0xFFFF} x{v[i + 1]}" for i in range(0, len(v), 2))


def pe_info(path: Path) -> dict | None:
    blob = path.read_bytes()
    if blob[:2] != b"MZ":
        return None
    try:
        pe = pefile.PE(data=blob)
    except pefile.PEFormatError:
        return {"kind": "NE"}
    fh, oh = pe.FILE_HEADER, pe.OPTIONAL_HEADER
    secs = [f"{s.Name.rstrip(b'\0').decode('latin1')} ({entropy(s.get_data()):.2f})" for s in pe.sections]
    ts = fh.TimeDateStamp
    imports = []
    for d in getattr(pe, "DIRECTORY_ENTRY_IMPORT", []):
        names = [(i.name or f"#{i.ordinal}".encode()).decode() for i in d.imports]
        imports.append((d.dll.decode(), names))
    exports = []
    if hasattr(pe, "DIRECTORY_ENTRY_EXPORT"):
        exports = [(s.name or f"#{s.ordinal}".encode()).decode() for s in pe.DIRECTORY_ENTRY_EXPORT.symbols]
    return {
        "kind": "DLL" if fh.Characteristics & 0x2000 else "EXE",
        "timestamp": f"0x{ts:08x} "
        + datetime.datetime.fromtimestamp(ts, datetime.UTC).strftime("%Y-%m-%d %H:%M:%S"),
        "linker": f"{oh.MajorLinkerVersion}.{oh.MinorLinkerVersion}",
        "rich": rich(pe),
        "sections": secs,
        "imports": imports,
        "exports": exports,
        "base": f"0x{oh.ImageBase:08x}",
        "entry": f"0x{oh.ImageBase + oh.AddressOfEntryPoint:08x}",
        "safedisc": safedisc(blob),
    }


def survey() -> None:
    rows = []  # (rel, size, md5, magic, path)
    for root in ROOTS:
        for path in sorted(p for p in (DISCS / root).rglob("*") if p.is_file()):
            with path.open("rb") as fh:
                head = fh.read(16)
            rows.append((path.relative_to(DISCS), path.stat().st_size, md5(path), magic(head), path))
    NOTES.mkdir(parents=True, exist_ok=True)
    with (NOTES / "corpus-md5.tsv").open("w", encoding="utf-8", newline="\n") as out:
        out.write("path\tsize\tmd5\n")
        for rel, size, h, _, _ in rows:
            out.write(f"{rel.as_posix()}\t{size}\t{h}\n")
    write_binaries(rows)
    write_inventory(rows)


def write_binaries(rows) -> None:
    lines = ["# Binaries (Grumpa CD)", "",
             "Generated by `engines/grumpa/tools/survey.py`. Every PE file except the",
             "redistributables (only counted). Section names carry their byte entropy.", ""]
    redist = 0
    for rel, size, h, _, path in rows:
        if path.suffix.lower() not in PE_EXTS:
            continue
        if is_redist(rel):
            redist += 1
            continue
        info = pe_info(path)
        if info is None:
            continue
        if info["kind"] == "NE":
            lines += [f"## `{rel.as_posix()}`", "", f"- {size:,} B, MD5 `{h}`, 16-bit NE executable", ""]
            continue
        lines += [f"## `{rel.as_posix()}`", "",
                  f"- {size:,} B, MD5 `{h}`, {info['kind']}, PE timestamp {info['timestamp']} UTC",
                  f"- linker {info['linker']}; Rich header: {info['rich']}",
                  f"- image base {info['base']}, entry {info['entry']}; sections {' '.join(info['sections'])}"]
        if info["safedisc"]:
            lines.append(f"- SafeDisc {info['safedisc']}")
        lines.append("- imports:")
        for dll, names in info["imports"]:
            lines.append(f"  - {dll} ({len(names)}): {' '.join(names)}")
        if info["exports"]:
            lines.append(f"- exports ({len(info['exports'])}): {' '.join(info['exports'])}")
        lines.append("")
    lines += [f"Redistributable PE files skipped: {redist}", ""]
    (NOTES / "binaries.md").write_text("\n".join(lines), encoding="utf-8")


def write_inventory(rows) -> None:
    sel = [r for r in rows if not is_redist(r[0])]
    lines = ["# Corpus inventory (Grumpa CD)", "",
             "Generated by `engines/grumpa/tools/survey.py`. Regenerate rather than hand-edit.",
             "Magic = first four bytes, quoted when printable, else hex. `cd/` is the ISO,",
             "`cab/` the InstallShield cabinet by file group. Redistributables excluded from",
             "the extension table.", ""]
    for root in ROOTS:
        rs = [r for r in rows if r[0].parts[0] == root]
        lines.append(f"- `games/grumpa/discs/{root}`: {len(rs):,} files, {sum(r[1] for r in rs):,} bytes "
                     f"({sum(is_redist(r[0]) for r in rs)} redistributable)")
    lines += ["", "Layout (files per directory, redistributables collapsed):", ""]
    dirs = Counter()
    for r in rows:
        parts = r[0].parts[:-1]
        if is_redist(r[0]):
            parts = parts[:2]
        dirs["/".join(parts)] += 1
    for d, n in sorted(dirs.items()):
        lines.append(f"- `{d}/` {n}")
    lines += ["", "| Ext | Files | Bytes | Magics (count) | Directories |", "|---|---:|---:|---|---|"]
    by_ext = defaultdict(list)
    for r in sel:
        by_ext[r[0].suffix.lower() or "(none)"].append(r)
    for ext, rs in sorted(by_ext.items(), key=lambda kv: -len(kv[1])):
        mags = Counter(r[3] for r in rs)
        top = ", ".join(f"`{m}` {n}" for m, n in mags.most_common(6))
        if len(mags) > 6:
            top += f", … {len(mags)} distinct"
        ds = sorted({"/".join(r[0].parts[:-1]) for r in rs})
        dtxt = ", ".join(ds) if len(ds) <= 4 else f"{', '.join(ds[:3])}, … {len(ds)} directories"
        lines.append(f"| `{ext}` | {len(rs):,} | {sum(r[1] for r in rs):,} | {top} | {dtxt} |")
    (NOTES / "corpus-inventory.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


def selftest() -> None:
    assert magic(b"RIFF....") == "'RIFF'"
    assert magic(b"\x11\x00\x00\x00") == "11000000"
    assert is_redist(Path("cd/DIRECTX8/DXSETUP.EXE")) and is_redist(Path("cab/_Engine_ScriptEngine/iscript.dll"))
    assert not is_redist(Path("cab/Profileshell/Grumpa.exe")) and not is_redist(Path("cd/Setup.exe"))
    assert entropy(bytes(range(256))) == 8.0 and entropy(b"aaaa") == 0.0
    blob = b"xx" + BOG + b"\0" * 14 + struct.pack("<3I", 2, 60, 52)
    assert safedisc(blob) == "2.60.052 (marker at file offset 0x2)", safedisc(blob)
    print("selftest ok")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--selftest", action="store_true")
    if ap.parse_args().selftest:
        selftest()
    else:
        survey()
