"""Walk the game data root and write engines/x3d/notes/corpus-inventory.md.

Read-only over the corpus (CLAUDE.md rule 7). The point is to answer, before any
decompilation: what file types exist, how many, how big, and does each extension have one
container format or several? A single magic prefix across every .O3D means one loader; six
distinct prefixes means the extension is a lie and the real discriminator is elsewhere.

    python engines/x3d/tools/inventory.py                       # default root, writes engines/x3d/notes/
    python engines/x3d/tools/inventory.py --root E:/Data -o -   # somewhere else, print to stdout
"""

from __future__ import annotations

import argparse
import statistics
import sys
from collections import Counter, defaultdict
from dataclasses import dataclass, field
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent / "parsers"))
from common import default_root  # noqa: E402

HEAD_BYTES = 32
MAGIC_BYTES = 4
# Above this many files, list heads for a representative sample instead of every file;
# Anim/ alone can run to thousands. --full overrides.
PER_FILE_LIST_LIMIT = 60


@dataclass
class ExtStats:
    ext: str = ""
    paths: list[Path] = field(default_factory=list)
    sizes: list[int] = field(default_factory=list)
    heads: list[bytes] = field(default_factory=list)
    magics: Counter = field(default_factory=Counter)
    dirs: Counter = field(default_factory=Counter)

    @property
    def count(self) -> int:
        return len(self.sizes)

    @property
    def total(self) -> int:
        return sum(self.sizes)


def collect(root: Path) -> dict[str, ExtStats]:
    stats: dict[str, ExtStats] = defaultdict(ExtStats)
    for path in sorted(root.rglob("*")):
        if not path.is_file():
            continue
        ext = path.suffix.lower() or "(no extension)"
        st = stats[ext]
        st.ext = ext
        with path.open("rb") as fh:
            head = fh.read(HEAD_BYTES)
        st.paths.append(path)
        st.sizes.append(path.stat().st_size)
        st.heads.append(head)
        st.magics[head[:MAGIC_BYTES]] += 1
        st.dirs[path.parent.relative_to(root).as_posix() or "."] += 1
    return dict(stats)


def histogram(sizes: list[int], width: int = 40) -> list[str]:
    """Log2 size buckets. Linear buckets are useless here: files run from a few bytes to
    tens of megabytes, so a linear histogram is one tall bar and a lot of whitespace."""
    buckets: Counter = Counter()
    for size in sizes:
        buckets[size.bit_length()] += 1
    if not buckets:
        return []
    peak = max(buckets.values())
    lines = []
    for bits in range(min(buckets), max(buckets) + 1):
        n = buckets.get(bits, 0)
        lo = 0 if bits == 0 else 1 << (bits - 1)
        hi = (1 << bits) - 1
        bar = "#" * max(1, round(width * n / peak)) if n else ""
        lines.append(f"{human(lo):>9} - {human(hi):<9} | {n:>5} {bar}")
    return lines


def human(n: float) -> str:
    for unit in ("B", "K", "M", "G"):
        if n < 1024 or unit == "G":
            return f"{int(n)}{unit}" if unit == "B" else f"{n:.1f}{unit}"
        n /= 1024
    return str(n)


def hexdump(data: bytes) -> str:
    return data.hex(" ") if data else "(empty)"


def printable(data: bytes) -> str:
    return "".join(chr(b) if 32 <= b < 127 else "." for b in data)


def head_rows(root: Path, s: ExtStats):
    rows = [
        (p.relative_to(root).as_posix(), size, head)
        for p, size, head in zip(s.paths, s.sizes, s.heads)
    ]
    if s.count <= PER_FILE_LIST_LIMIT:
        return rows
    # Representative sample: the extremes of each magic group are where a format variant
    # or a truncated file shows up.
    by_magic: dict[bytes, list] = defaultdict(list)
    for row in rows:
        by_magic[row[2][:MAGIC_BYTES]].append(row)
    sample = []
    for group in by_magic.values():
        group.sort(key=lambda r: r[1])
        sample.append(group[0])
        if len(group) > 1:
            sample.append(group[-1])
    return sorted(sample)


def render(root: Path, stats: dict[str, ExtStats]) -> str:
    out: list[str] = []
    w = out.append

    total_files = sum(s.count for s in stats.values())
    total_bytes = sum(s.total for s in stats.values())

    w("# Corpus inventory")
    w("")
    w(f"- **Root:** `{root}`")
    w(f"- **Files:** {total_files:,}")
    w(f"- **Total size:** {total_bytes:,} bytes ({human(total_bytes)})")
    w(f"- **Extensions:** {len(stats)}")
    w("")
    w("Generated by `engines/x3d/tools/inventory.py`. Regenerate rather than hand-edit.")
    w("")
    w("## Summary")
    w("")
    w("| Ext | Files | Total | Min | Median | Max | Distinct magics |")
    w("|---|---:|---:|---:|---:|---:|---:|")
    for ext, s in sorted(stats.items(), key=lambda kv: -kv[1].total):
        w(
            f"| `{ext}` | {s.count:,} | {human(s.total)} | {human(min(s.sizes))} "
            f"| {human(int(statistics.median(s.sizes)))} | {human(max(s.sizes))} "
            f"| {len(s.magics)} |"
        )
    w("")
    w(
        "One distinct magic per extension means one container format. More than one means "
        "either a variant field lives in the first four bytes, or the extension covers "
        "unrelated formats. Check before writing a spec."
    )
    w("")

    for ext, s in sorted(stats.items(), key=lambda kv: -kv[1].total):
        w(f"## `{ext}` - {s.count:,} file(s), {human(s.total)}")
        w("")

        w("Directories:")
        w("")
        for d, n in s.dirs.most_common(20):
            w(f"- `{d}` - {n}")
        if len(s.dirs) > 20:
            w(f"- ... and {len(s.dirs) - 20} more directories")
        w("")

        w("Size histogram (log2 buckets):")
        w("")
        w("```")
        out.extend(histogram(s.sizes))
        w("```")
        w("")

        w(f"Magic prefixes (first {MAGIC_BYTES} bytes):")
        w("")
        w("| Count | Hex | ASCII |")
        w("|---:|---|---|")
        for magic, n in s.magics.most_common():
            w(f"| {n} | `{hexdump(magic)}` | `{printable(magic)}` |")
        w("")

        w(f"First {HEAD_BYTES} bytes:")
        w("")
        w("| File | Size | Hex | ASCII |")
        w("|---|---:|---|---|")
        for rel, size, head in head_rows(root, s):
            w(f"| `{rel}` | {size:,} | `{hexdump(head)}` | `{printable(head)}` |")
        if s.count > PER_FILE_LIST_LIMIT:
            w("")
            w(
                f"_{s.count:,} files exceeds the {PER_FILE_LIST_LIMIT}-row listing limit; "
                "showing the smallest and largest file per distinct magic prefix. "
                "Re-run with `--full` for every file._"
            )
        w("")

    return "\n".join(out) + "\n"


def main() -> int:
    global PER_FILE_LIST_LIMIT

    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--root", type=Path, default=None, help="data root")
    ap.add_argument(
        "-o",
        "--out",
        default=None,
        help="output path, or '-' for stdout (default: engines/x3d/notes/corpus-inventory.md)",
    )
    ap.add_argument("--full", action="store_true", help="list every file, no row limit")
    args = ap.parse_args()

    root = args.root or default_root()
    if not root.is_dir():
        print(f"data root not found: {root}", file=sys.stderr)
        return 2
    if args.full:
        PER_FILE_LIST_LIMIT = 10**9

    stats = collect(root)
    if not stats:
        print(f"no files under {root}", file=sys.stderr)
        return 2
    text = render(root, stats)

    if args.out == "-":
        sys.stdout.write(text)
        return 0

    out = (
        Path(args.out)
        if args.out
        else Path(__file__).resolve().parents[1] / "notes" / "corpus-inventory.md"
    )
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text, encoding="utf-8")
    print(f"wrote {out} ({sum(s.count for s in stats.values()):,} files, {len(stats)} exts)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
