# ScummVM config for running the engine during development.
[scummvm]
lastselectedgame=monet
enable_unsupported_game_warning=false
gfx_mode=surfacesdl
scale_factor=1
versioninfo=2026.3.1git
gui_language=C

