# ScummVM config for running the engine during development.
[scummvm]
lastselectedgame=monet
last_window_width=1280
versioninfo=2026.3.1git
enable_unsupported_game_warning=false
gfx_mode=surfacesdl
scale_factor=1
window_maximized=false
gui_language=C
last_window_height=960

