"""Write engines/<engine>/notes/MAP.md: every source file of the engine with its line count,
what it is for (its first comment after the licence header) and the classes it declares,
so an agent orients in one short read instead of exploring the tree. Rerun after adding
files (publish does not); a file without a comment shows up as "(no description)", which
is a hint to write one.

    python tools/engine_map.py grumpa
    python tools/engine_map.py --all
    python tools/engine_map.py --selftest
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
ENGINES = [l.split()[0] for l in (Path(__file__).resolve().parents[1] / "tools" / "engines.txt").read_text().splitlines() if l.strip() and not l.startswith("#")]
CLASS = re.compile(r"^\s*(?:class|struct)\s+(\w+)\s*(?::[^{;]*)?\{", re.M)


def describe(text: str) -> str:
    body = re.sub(r"\A\s*/\*.*?\*/", "", text, count=1, flags=re.S)  # the GPL header
    body = re.sub(r"\A(\s*#\w+[^\n]*\n|\s*namespace \w+ \{[^\n]*\n|\s*(?:class|struct) \w+;[^\n]*\n|\s*\n)*", "", body)
    m = re.match(r"\s*/\*\*?(.*?)\*/", body, re.S) or re.match(r"\s*((?://[^\n]*\n)+)", body)
    if not m:
        return ""
    lines = [re.sub(r"^\s*(\*|//)\s?", "", l).strip() for l in m.group(1).splitlines()]
    text = " ".join(l for l in lines if l)
    return re.split(r"(?<=[.;])\s", text, maxsplit=1)[0][:200]


def build(engine: str) -> Path:
    root = Path("C:/scummvm-dev") / engine / "engines" / engine
    rows = []
    for f in sorted(root.rglob("*")):
        if f.suffix not in (".h", ".cpp") or not f.is_file():
            continue
        text = f.read_text(encoding="utf-8", errors="replace")
        classes = CLASS.findall(text) if f.suffix == ".h" else []
        desc = describe(text)
        header = f.with_suffix(".h")
        if not desc and f.suffix == ".cpp" and header.exists():
            desc = describe(header.read_text(encoding="utf-8", errors="replace"))
        rows.append((f.relative_to(root).as_posix(), text.count("\n"), desc, classes))
    out = REPO / "engines" / engine / "notes" / "MAP.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    lines = [f"# {engine} engine map", "",
             f"Generated by `tools/engine_map.py {engine}` from `C:\\scummvm-dev\\{engine}\\engines\\{engine}` "
             "(branch " + f"`{engine}-dev`). Do not edit; improve the files' comments instead.", "",
             f"{len(rows)} files, {sum(r[1] for r in rows):,} lines.", "",
             "| file | lines | purpose | classes |", "|---|---|---|---|"]
    for path, n, desc, classes in rows:
        lines.append(f"| `{path}` | {n} | {desc.replace('|', '/') or '(no description)'} | {', '.join(classes[:8])} |")
    out.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    missing = sum(1 for r in rows if not r[2])
    print(f"{engine}: {len(rows)} files -> {out.relative_to(REPO)} ({missing} without a description)")
    return out


def selftest() -> None:
    src = "/* GPL\n * header */\n\n#ifndef X_H\n#define X_H\n\n/** Loads scenes. More detail. */\nclass Scene : public Base {\n};\n"
    assert describe(src) == "Loads scenes.", describe(src)
    assert CLASS.findall(src) == ["Scene"]
    assert describe("/* GPL */\n// Draws the HUD.\n// Second line.\nint x;") == "Draws the HUD."
    print("engine_map selftest ok")


if __name__ == "__main__":
    if sys.argv[1:] == ["--selftest"]:
        selftest()
    elif sys.argv[1:] == ["--all"]:
        for e in ENGINES:
            build(e)
    elif len(sys.argv) == 2:
        build(sys.argv[1])
    else:
        print(__doc__)
        sys.exit(2)
